Retry: Student view only push
apuder/advising pull request #2
Opened 2018-12-22 09:29 UTC by shamedone

Hi Dr Puder, 

Ok so I looked over what you wrote and am retrying the student view only pull request again. I have squashed all the related commits together and this pull only looks at provide the resources for a student read_only_view, although the button to access it is still commented out in this pull as it does not serve a real a purpose atm. 

I just want to be clear on best practices, I have sorta restarted and am doing things in this process for each feature I am working on: create feature branch, edit and commit as much as I wish until the feature is done. Then merge back into my master branch and create a pull request. If that works, then I will follow that model as I continue to update the page. 

As always, let me know if you have any questions. If this process looks good I will begin sending more pull requests in smaller feature size chunks. Thanks!

 -Tom

2018-12-31 12:17 UTC, apuder requested changes
Sorry for the slow feedback. I left come comments. Please make the necessary changes. In general: one PR should focus on one feature and should contain only one commit. How you organize your branches and commits at your end is up to you. The log message for the one commit should give a high-level summary. No need to document the individual steps.

2018-12-31 12:17 UTC, apuder commented on src/main/java/edu/sfsu/AdvisingServlet.java
> +            String readonly = request.getParameter("readonly");
It is not a good idea to let the client tell us whether the view should be read-only or not. That can easily be hacked by a tech-savvy person. The server should "know" whether the currently logged-in user is a superuser (read/write access) or a student (read-only access). Ultimately I want to integrate this with the campus SSO. But for now I suggest to "fake" something. Perhaps add a second password for read-only access in the property file.

2018-12-31 12:17 UTC, apuder commented on src/main/java/edu/sfsu/HtmlFormatter.java
> +        generateCheckpoint(fragment, student.id, student.checkpointOralPresentation,
Why do you need to duplicate these lines? A little further below there is exactly the same statement.

2018-12-31 12:17 UTC, apuder commented on src/main/webapp/index.html
> +            if (readonly =="true"){
Can you please do consistent formatting?  Please insert spaces where appropriate. Also do this for Java code.

2018-12-31 12:17 UTC, apuder commented on src/main/webapp/index.html
> +    <div class="mdl-layout__tab-panel" id="senior_advising_read_only" style="display: none">
I suggest you remove all this HTML and decide on the server side (based on which password the user typed in) whether you send the editable or read-only HTML. I don't see the need for duplicating this HTML.

2019-01-02 20:55 UTC, shamedone commented
Hi Dr Puder, 

Thanks for your feedback. As I looked over this code and feedback, it strikes me that this read only view feature was more of a way for me to get my to get familiar with the software than a change that was actually requested from you or Dr. Hsu. So what I suggest is maybe closing or setting aside this pull request for the time being, and then me sending a new pull request for one of the other features I have worked on, that way you can look at some of the more useful changes while I can reevaluate how best to implement the comments you outlined in the above. Let me know! Thanks!

 -Tom

2019-01-03 16:57 UTC, apuder commented
OK, I will close this PR for now. Perhaps we should first discuss the scope of each PR. E.g., I suggest to make the test/dummy DB its own PR. This way it will be much easier for me to understand and follow your changes.

2019-01-03 16:57 UTC, closed without merging